version: '3.8'
services:
  mysql:
    image: mysql:latest  # MySQL 이미지 사용
    container_name: mysql_container
    ports:
      - "3306:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: "1234"        # MySQL root 계정 비밀번호
      MYSQL_DATABASE: dohyundatabase       # MySQL 생성할 데이터베이스 이름
      MYSQL_USER: root                 # MySQL 사용자 계정
      MYSQL_PASSWORD: "1234"             # 사용자 계정 비밀번호
    networks:
      - my_network
    
  node-mysql: # 이미지 이름이 된다.(폴더명-node)
    build: .
    container_name: node_server02
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - my_network
    environment:
      # MYSQL_URI: mysql://root:1234@mysql:3306/dohyundatabase  # MySQL 연결 URI
      - MYSQL_URI: mysql://mysql_container:3306/dohyundatabase  # MySQL 연결 URI
    # command: ["mysql:3306", "--", "node", "app.js"]
    command: ["node", "app.js"]

# 네트워크 설정
networks:
  my_network:
    driver: bridge