version: '3.8'
services:
  mariadb:
    image: mariadb:latest  # MariaDB 이미지 사용
    container_name: mariadb_container
    ports:
      - "3306:3306"  # MariaDB 기본 포트
    environment:
      MYSQL_ROOT_PASSWORD: 1234         # MariaDB root 계정 비밀번호(최고관리자, DB생성)
      MYSQL_DATABASE: mydatabase        # MariaDB 생성할 데이터베이스 이름
      MYSQL_USER: root                  # MariaDB 사용자 계정
      MYSQL_PASSWORD: 1234              # 사용자 계정 비밀번호(사용시에 사용할 번호)

  node:
    build: .
    container_name: node_server
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    environment:
      MARIADB_URI: mariadb://root:password@mariadb:3306/mydatabase
    command: ["./wait-for-it.sh", "mariadb:3306", "--", "node", "server.js"]